# Generated by Django 3.2.5 on 2021-07-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pprice', models.IntegerField(default='0')),
                ('category', models.CharField(choices=[('Mobile', 'Mobile'), ('Appliances', 'Appliances'), ('Sports', 'Sports'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty')], default='-----', max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
            ],
        ),
    ]
